#### Python is a popular programming language. However, it is essentially a scripting language. It has a plethora of applications. It helps ignore multiple syntactical notations seen in fellow languages like C and Java. Hence, it is quite easier to learn Python.

In [1]:
# PYTHON VARIABLES

In [2]:
# variables are placeholders for various values required in a program

x = 2
x = x + 7

a = 4
b = 3

print(x)
print(a+b)

9
7


In [3]:
y = 2
z = 3
y+z

5

In [4]:
_ + 2 # _ represents output of the previous operation

7

In [5]:
# LISTS

In [6]:
nums = [34,43,59,67,68]

In [7]:
# accessing elements (slicing)

print(nums[2])
print(nums[3:])
print(nums[-1])

59
[67, 68]
68


In [8]:
values = [9.5,'Starc',25] # list comprising of different data types

In [9]:
values.append(43) # adds an element to the end of the list

In [10]:
values.insert(2,77) # insert at the specified positiom

In [11]:
values.remove(9.5) # remove an element from the list

In [12]:
values

['Starc', 77, 25, 43]

In [13]:
values.pop(1) # deleting an element at an index position

77

In [14]:
values

['Starc', 25, 43]

In [15]:
values.pop()

43

In [16]:
del values

In [17]:
list1 = [23,54,3,4,5,6,77,89]

In [18]:
min(list1)

3

In [19]:
max(list1)

89

In [20]:
sum(list1)

261

In [21]:
list1.sort()

In [22]:
list1

[3, 4, 5, 6, 23, 54, 77, 89]

In [23]:
# TUPLES AND SETS

In [24]:
# Tuple is similar to list. However, tuples are not mutable.
# Tuple does not support item assignment.

tuple1 = () # creating an empty tuple.

In [25]:
tuple1 = (21,36,14,43,99)

In [26]:
tuple1[1] # fetching a value from a tuple.

36

In [27]:
# Set is a collection of unique elements.

set1 = {22,23,24,25} # sequence is not followed/required

In [28]:
set1

{22, 23, 24, 25}

In [29]:
set2 = {2,2,2,2,2,7}

In [30]:
set2

{2, 7}

In [31]:
# set uses a technique called hash which speeds up the search for a particular element.

# set object does not support indexing.

In [32]:
# DICTIONARIES

In [33]:
data = dict() # creating an empty dictionary

In [34]:
data

{}

In [35]:
data1 = {1:'Purdy',2:'McCaffrey',3:'Kittle',4:'Trent'}

In [36]:
data1[3] # access an element

'Kittle'

In [37]:
data1.get(3) # access an element

'Kittle'

In [38]:
data1.get(5,'Not Found')

'Not Found'

In [39]:
# implementing a dictionary using a list

keys = [1,2,3,4,5]

values = ['Betts','Freeman','Ohtani','Glasnow','Lux']

data = dict(zip(keys,values))

In [40]:
data

{1: 'Betts', 2: 'Freeman', 3: 'Ohtani', 4: 'Glasnow', 5: 'Lux'}

In [41]:
data2 = zip(keys,values)

In [42]:
data2

In [43]:
data1.clear() # clear the dictionary entries

In [44]:
data[6] = 'Yamamoto'

In [45]:
data

{1: 'Betts', 2: 'Freeman', 3: 'Ohtani', 4: 'Glasnow', 5: 'Lux', 6: 'Yamamoto'}

In [46]:
del data[6] # deleting an entry

In [47]:
prog = {'JS':'Atom', 'CS':'VS', 'Python':['Pycharm','Sublime'],'Java':{'Java SE','NetBeans'}}

In [48]:
prog

{'JS': 'Atom',
 'CS': 'VS',
 'Python': ['Pycharm', 'Sublime'],
 'Java': {'Java SE', 'NetBeans'}}

In [ ]:
# help command provides helpful documentation.

# help()

In [1]:
num = 7

id(num) # gives us address location of the variable 'num'.

2561611753968

In [2]:
"""
OPERATORS IN PYTHON:

1. Arithmetic Operators

2. Assignment Operators

3. Unary Operators

4. Relational Operators

5. Logical Operators
""" 

'\nOPERATORS IN PYTHON:\n\n1. Arithmetic Operators\n\n2. Assignment Operators\n\n3. Unary Operators\n\n4. Relational Operators\n\n5. Logical Operators\n'

In [3]:
bin(25)

'0b11001'

In [4]:
oct(25)

'0o31'

In [5]:
hex(25)

'0x19'

In [6]:
# swap two variables

a = 5
b = 6

# swap using XOR (^) Operator

a = a ^ b
b = a ^ b
a = a ^ b

In [7]:
print(a)
print(b)

6
5


In [8]:
# Mathematical Functions

import math 

x = math.sqrt(25)

In [9]:
x

5.0

In [10]:
y = math.floor(2.9)

In [11]:
y = math.ceil(2.2)

In [12]:
y

3

In [13]:
print(math.pow(3,2))

9.0


In [16]:
"""
Fetching user input: Use input().

Input is always fetched as a String.

""" 

x = input()

Hello Yoshinobu


In [18]:
ch = input('Enter a char ')[0]
print(ch)

Enter a char pqr
p


In [19]:
# finding cube of the number:

value = int(input('Enter an integer: '))
result = math.pow(value,3)

Enter an integer: 9


In [20]:
result

729.0

In [23]:
# If Statement: Conditional block of statements which allow execution based on the evaluation of a 'test condition'.

# BASIC SYNTAX:

if True:
    #statements
    print()

In [24]:
# Else: The else block is executed iff the if condition evaluates to False.

if 2 > 3:
    print("True")
else:
    print("False")

False


In [25]:
# Elif: Used when we have to check/evaluate multiple conditions.

In [1]:
# LOOPS: Repeatedly execute a set of statements until the test condition evaluates to False.

# WHILE LOOP:

i = 1
while i<21:
    if i % 3 == 0 or i % 5 == 0:
        i += 1
        continue
    print(i,end = " ")
    i += 1

1 2 4 7 8 11 13 14 16 17 19 

In [5]:
character = '#'

i = 1 
j = 0

while i<=4:
    j = 1
    while j<=4:
        print(character,end=" ")
        j += 1
    i += 1
    print()

# # # # 
# # # # 
# # # # 
# # # # 


In [7]:
# FOR LOOOP:

for i in range(1,23):
    square = i * i
    if square < 500:
        print(square, end = " ")      

1 4 9 16 25 36 49 64 81 100 121 144 169 196 225 256 289 324 361 400 441 484 

In [13]:
number = 2

if number > 1:
    for i in range(2, int(number**0.5)+1):
        if number % i == 0:
            print(False)
    print(True)

True


In [18]:
a = 0
b = 1

print(a,end = " ")

for i in range(1,50):
    sum1 = a + b
    print(sum1,end = " ")
    a = b
    b = sum1

0 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765 10946 17711 28657 46368 75025 121393 196418 317811 514229 832040 1346269 2178309 3524578 5702887 9227465 14930352 24157817 39088169 63245986 102334155 165580141 267914296 433494437 701408733 1134903170 1836311903 2971215073 4807526976 7778742049 12586269025 

In [20]:
# FLOW REGULATORY STATEMENTS:

""" 
1. Break
2. Continue
3. Pass
"""

' \n1. Break\n2. Continue\n3. Pass\n'

In [27]:
for i in range(4):
    for j in range(4-i):
        print('#',end=' ')
    print( )

# # # # 
# # # 
# # 
# 


In [29]:
for i in range(1,5):
    for j in range(i,5):
        print(j,end = ' ')
    print()

1 2 3 4 
2 3 4 
3 4 
4 


In [35]:
for i in range(1,5):
    for j in range(1,i+1):
        print(j,end = ' ')
    print()

1 
1 2 
1 2 3 
1 2 3 4 


In [38]:
a = "ABCD"
b = "PQR"
for i in range(4):
    for j in range(3):
        print(a[0:i+1],end = "")
        print(b[i:j+3],end = "")
        break
    print()

APQR
ABQR
ABCR
ABCD


In [40]:
# FOR-ELSE

for num in range(4):
    if num % 5 == 0:
        print(num)
        break
else:
    print("Not Found.")

0


In [41]:
num = 7

for i in range(2,num):
    if num % i == 0:
        print("Not Prime.")
        break
else:
    print("Prime.")

Prime.


In [42]:
from array import *

vals = array('i',[5,9,8,4,2]) # specify proper type code
print(vals)

array('i', [5, 9, 8, 4, 2])


In [44]:
print(vals.buffer_info()) # output is in the form of (address, size).

(2415186105136, 5)


In [45]:
vals.reverse()

In [46]:
vals

array('i', [2, 4, 8, 9, 5])

In [47]:
arr = array('i',[])

n = int(input('Enter the length of the array: '))

for i in range(n):
    x = int(input('Enter the next value: '))
    arr.append(x)
print(arr)

Enter the length of the array: 3
Enter the next value: 1
Enter the next value: 2
Enter the next value: 7
array('i', [1, 2, 7])


In [48]:
# NUMPY: Helps work with multidimensional arrays.

import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [49]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [50]:
arr = np.array([1,2,3,4,5.0])
print(arr.dtype)

float64


In [52]:
arr = np.linspace(0,15,16) # Range [0-15] is divided into 16 parts.
print(arr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [53]:
arr = np.logspace(1,40,5)
print(arr)

[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]


In [58]:
arr = np.arange(1,15,2)
print(arr)

[ 1  3  5  7  9 11 13]


In [59]:
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [60]:
arr = np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [62]:
arr1 = np.array([[1,2,3],
                [4,5,6]])

print(arr1.shape) # output is (no. of rows, no. of columns)

(2, 3)


In [63]:
arr2 = arr1.flatten()

In [64]:
arr2

array([1, 2, 3, 4, 5, 6])

In [66]:
arr3 = arr1.reshape(3,2)

In [67]:
arr3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [68]:
m = np.matrix('1 2 3; 4 5 6; 1 6 7')

In [69]:
print(np.diagonal(m)) # print the diagonal elements.

[1 5 7]


In [70]:
print(m.min())

1


In [71]:
n = np.matrix('1 1 1; 1 1 1; 1 1 1')

In [73]:
m3 = m * n # multiplication of 2 matrices 

In [74]:
m3

matrix([[ 6,  6,  6],
        [15, 15, 15],
        [14, 14, 14]])

In [ ]:
# FUNCTIONS

def function_name():
    # function body
    #..............
    # return value (optional)
    
function_name()  # calling the particular function.

There is no pass by value or pass by reference in Python.

In [ ]:
# Types of arguments:

Formal Arguments: Used when defining the function.
    
Actual Arguments: Are passed to the function during the function call.
    
    a. Position: Mention variable name during the function call to ensure values are assigned to the correct function variables.
        
    b. Default: Default value for a variable. EX: def person(name, age = 18)
            
    c. def sum(a, *b): For b you can pass a tuple of values.

In [2]:
# KWARGS:

def person(name, **data):
    print(name)
    print(data)

person('Shohei',age = 29, city = 'LA',number = 700)

Shohei
{'age': 29, 'city': 'LA', 'number': 700}


In [5]:
a = 10

print(id(a))

def something():
    a = 9
    x = globals()['a']
    
    print(id(x))
    print("in function", a)
    
something()

1917835962960
1917835962960
in function 9


In [6]:
def factorial(n):
    if n <= 1:
        return 1
    else:
        long = 1
        while n>0:
            long = long * n
            n = n - 1
    return long

In [7]:
factorial(5)

120

In [8]:
# RECURSION: Calling a function within itself.

def factorial_r(n):
    if n <=1:
        return 1
    else:
        return n * factorial(n-1)

In [9]:
factorial_r(5)

120

In [10]:
# Anonymous Functions: Functions without name (Lambda).

f = lambda a : a*a  # lambda variables : expression

result = f(5)

In [11]:
result

25

In [12]:
# FILTER

nums = [3,2,6,8,4,6,2,9]
evens = list(filter(lambda n : n%2 == 0,nums))

evens

[2, 6, 8, 4, 6, 2]

In [13]:
# MAP

doubles = list(map(lambda n : n+2,evens))

doubles

[4, 8, 10, 6, 8, 4]

In [14]:
# REDUCE

from functools import reduce

sum = reduce(lambda a,b : a+b,doubles)

sum

40

In [18]:
# Object Oriented Programming:

class Computer:
    
    # ATTRIBUTES
    #------------
    def __init__(self,cpu,ram):
        self.cpu = cpu
        self.ram = ram
        
    # BEHAVIOUR
    #-------------
    def config(self):
        print("i5, 16GB, 1TB")
        
com1 = Computer('i5',16)

print(type(com1))

<class '__main__.Computer'>


In [16]:
com1.config() or Computer.config(com1)

i5, 16GB, 1TB


In [ ]:
Size of an object depends on the number of variables.

In [19]:
class Car:
    
    wheels = 4
    
    def __init__(self):
        self.mil = 10
        self.com = "BMW"
        
c1 = Car()
c2 = Car()

c1.mil = 8

print(c1.mil,c1.com)
print(c2.mil,c2.com)

8 BMW
10 BMW


In [20]:
class Student:
    
    def __init__(self,m1,m2,m3):
        self.m1 = m1
        self.m2 = m2
        self.m3 = m3
        
    def avg(self):
        return (self.m1 + self.m2 + self.m3)/3
    
s1 = Student(34,67,32)
s2 = Student(89,32,12)

In [21]:
s1.avg()

44.333333333333336

In [22]:
# INNER CLASS

class Student:
    
    def __init__(self,name,rollno):
        self.name = name
        self.rollno = rollno
        self.lap = self.Laptop() # method 1 of calling the inner class [making an object of inner class outside the outer class].
        
    def show(self):
        print(self.name, self.rollno)
        
    class Laptop:
        
        def __init__(self):
            self.brand = 'HP'
            self.cpu = 'i5'
            self.ram = 8
        
s1 = Student('Purdy',2)

laptop1 = s1.lap.brand

In [23]:
laptop2 = Student.Laptop() # method 2 of making an object of inner class outside the outer class.

In [25]:
# Inheritance

class A:
    def feature1(self):
        print('Feature 1 Working')
        
    def feature2(self):
        print('Feature 2 Working')
        
class B(A): # B inherits from class A.
    def feature3(self):
        print('Feature 3 Working')
        
    def feature4(self):
        print('Feature 4 Working')
        
b1 = B()

b1.feature1()
b1.feature2()
b1.feature3()
b1.feature4()

Feature 1 Working
Feature 2 Working
Feature 3 Working
Feature 4 Working


In [26]:
class C(B): # Class C inherits from Class B
    def feature5(self):
        print('Feature 5 Working')
        
c1 = C()

c1.feature1()
c1.feature2()
c1.feature3()
c1.feature4()
c1.feature5()

Feature 1 Working
Feature 2 Working
Feature 3 Working
Feature 4 Working
Feature 5 Working


In [ ]:
Multiple inheritance:
    
def class C(A,B): # Assuming class B has not inherited from class A.

In [28]:
# CONSTRUCTOR IN INHERITANCE

class A1:
    def feature1(self):
        print('Feature 1 Working')
        
    def feature2(self):
        print('Feature 2 Working')
        
class B1(A1):
    def __init__(self):
        super().__init__()          # can access features of the parent class.
        
    def feature3(self):
        print('Feature 1 Working')
        
    def feature4(self):
        print('Feature 2 Working')
        
a1 = B1()

 in B Init


In [ ]:
class C(A,B):
    
    def __init__(self):
        super().__init__() # Bias Towards Class A.
        
Method Resolution Order(MRO): Multiple Inheritance starts from left to right.

In [ ]:
# Polymorphism

Ability to take multiple forms.

In [ ]:
Method Overloading:
    
    def average(a,b)
    
    def average(a,b,c)

In [29]:
# METHOD OVERLOADING
class Student:
    
    def __init__(self,m1,m2):
        self.m1 = m1
        self.m2 = m2
        
    def sum(self,a=None,b=None,c=None):
        
        if a!=None and b!=None and c!=None:
            s = a+b+c
        elif a!=None and b!=None:
            s = a+b
        else:
            s = a
        
        return s
    
s1 = Student(58,69)

print(s1.sum(5,9,6))

14


In [30]:
# METHOD OVERRIDING

class A:
    
    def show(self):
        print("in A Show")
        
class B(A):
    pass
        
a1 = B()
a1.show()

in A Show


In [31]:
# METHOD OVERRIDING

class A:
    
    def show(self):
        print("in A Show")
        
class B(A):
    
    def show(self):
        print("in B Show") #Overrides A.
        
a1 = B()
a1.show()

in B Show


In [ ]:
# ABSTRACT CLASS: Class that constitutes abstract methods. (Atleast 1 abstract method).

# ABSTRACT METHOD: Methods which have only a declaration but no formal definition are referred to as abstract methods.

class Comp:
    def process(self):
        pass # No functionality for the method.
    
#In Python, abstract classes do not allow the creation of objects. 

from abc import ABC, abstractmethod

class Comp(ABC):
    @abstractmethod
    def process(self):
        pass
    
cmp = Comp() # cannot create an object of that class.

In [3]:
# ITERATORS

nums = [7,8,9,5]

for i in nums:
    print(i,end= ' ')

7 8 9 5 

In [4]:
nums = [7,8,9,10]

it = iter(nums)

print(it.__next__())

7


In [5]:
# GENERATORS

def topten():
    
    n = 1
    
    while n <= 10:
        square = n*n
        yield square  # creating iterator using generator
        n = n+1
        
values = topten()

for i in values:
    print(i, end = ' ')

1 4 9 16 25 36 49 64 81 100 

In [ ]:
# ERRORS

1. Compile Time: Essentially syntactical errors.

2. Logical: Yields the wrong output.

3. Run Time: Error during the run-time/execution.

In [9]:
# HANDLING EXCEPTIONS (TRY & EXCEPT)
try:
    a = 5
    b = 0
    sum1 = a/b
except Exception: # except ZeroDivisionError
    print('Zero Division Error')
    
try:
    a = 5
    b = 0
    sum1 = a/b
except ZeroDivisionError: 
    print('Zero Division Error')
    
try:
    a = 5
    b = 0
    sum1 = a/b
except Exception as e: 
    print(e)

Zero Division Error
Zero Division Error
division by zero


In [10]:
# It is important to close any resource that we have opened/accessed like a file, database connection.

# This is where we use the finally block.

try:
    a,b = 5,2
    print('Resource Open.')
    
except Exception as e:
    print(e)
    
finally: # Clean up (close) your resources.
    print('Resource Closed')

Resource Open.
Resource Closed


In [11]:
# THREADS

When a task is broken down into smaller tasks, each task is referred to as a thread.

In [12]:
class Hello:
    def run(self):
        for i in range(5):
            print('Hello')
    
class Hi:
    def run(self):
        for i in range(5):
            print('Hi')
            
t1 = Hello()
t2 = Hi()

t1.run()
t2.run()

Hello
Hello
Hello
Hello
Hello
Hi
Hi
Hi
Hi
Hi


In [ ]:
# Parallel Execution 

Execute 2 functions simultaneously. By default, every exceution has one thread. This thread is called the main thread.

In [3]:
# IMPLEMENTING THREADING

from time import sleep
from threading import *

class Hello(Thread):
    def run(self):
        for i in range(5):
            print('Hello')
            sleep(1)
            
class Hi(Thread):
    def run(self):
        for i in range(5):
            print('Hi')
            sleep(1)
t1 = Hello()
t2 = Hi()

t1.start() #t1 thread
sleep(0.2)
t2.start() #t2 thread

# t1 and t2 are joined to ensure bye is printed after all the Hello and Hi Statements.
t1.join()
t2.join()

print("Bye") #statement is executed by the main thread.

# two threads are created to execute t1 and t2.

# Internally, the run method is called.

Hello
Hi
Hello
Hi
Hello
Hi
Hello
Hi
Hello
Hi


In [ ]:
# File Handling

# open("Filename",'mode')

# modes: r (read), w (write), wb (append)

file = open('Filename','r')

print(f.readline()) # prints the first line

print(f.readline()) # each readline statement execution proceeds to print the next line.

In [7]:
# LINEAR SEARCH

def linear_search(arrays,key):
    for i in arrays:
        if i == key:
            return True
    return False

arr = [5,8,4,6,9,2]

key = 9

linear_search(arr,key)

True

In [2]:
def binary_search(arrays,key):
    
    l = 0
    u = len(arrays) - 1
    
    while l <= u:
        mid = (l+u)//2
        
        if arrays[mid] == key:
            return True
        else:
            if arrays[mid] < key:
                l = mid
            else:
                u = mid
    
arr = [5,8,4,6,9,2]

key = 9

binary_search(arr,key)               

True

In [6]:
def b_s(arr,low,high,x):
    
    if high>=low:
        
        mid = (high+low)//2
        
        if arr[mid] == x:
            return mid
        elif arr[mid] > x:
            return b_s(arr,low,mid-1,x)
        else:
            return b_s(arr,mid+1,high,x)
    else:
        return -1

In [7]:
arr = [ 2, 3, 4, 10, 40 ]
x = 10

In [8]:
result = b_s(arr, 0, len(arr)-1, x)
 
if result != -1:
    print("Element is present at index", str(result))
else:
    print("Element is not present in array")

Element is present at index 3


In [11]:
def bubble_sort(arrays):
    for i in range(len(arrays)-1):
        for j in range(i+1,len(arrays)):
            if arrays[i] > arrays[j]:
                arrays[i],arrays[j] = arrays[j],arrays[i]
    return arrays

In [12]:
array1 = [3,1,8,2,6,5]
bubble_sort(array1)

[1, 2, 3, 5, 6, 8]

In [13]:
array2 = [10,9,8,7,6,5,4,3,2,1]
bubble_sort(array2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [14]:
def selection_sort(arrays):
    for i in range(len(arrays)-1):
        minpos = i
        for j in range(i,len(arrays)):
            if arrays[j] < arrays[minpos]:
                minpos = j
        arrays[i],arrays[minpos] = arrays[minpos],arrays[i]

In [15]:
array2 = [10,9,8,7,6,5,4,3,2,1]
selection_sort(array2)

In [16]:
array2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
# MYSQL CONNECTION

# pip install mysql-connector

import mysql.connector

mydb = mysql.connector.connect(host='',user='',passwd='')

mycursor = mydb.cursor()

mycursor.execute("show databases;")

for x in mycursor:
    print(i)
    
mycursor.execute("select * from student;")

result = mycursor.fetchall()

for i in result:
    print()

In [17]:
# ZIP Function

names = ['Steph','Klay','Draymond']

position = ['PG','SG','DF']

zipped = zip(names,position)

print(zipped)

In [18]:
list(zipped)

[('Steph', 'PG'), ('Klay', 'SG'), ('Draymond', 'DF')]